version: 0.2

phases:
  install:
    commands:
      - echo "Debugging directory contents..."
      - pwd
      - ls -la
      - echo "Installing dependencies..."
      - npm install || (echo "npm install failed - checking package.json" && ls -la package.json && exit 1)

  build:
    commands:
      - echo "Building the app..."
      - npm run build

  post_build:
    commands:
      - echo "Uploading build artifacts to S3..."
      - aws s3 sync build/ s3://paynet-tgp-bucket-1/tgp-frontend-build/tgp-frontend-pipeline --delete

artifacts:
  files:
    - '**/*'
  base-directory: build