version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the app..."
      - npm run build

  post_build:
    commands:
      - echo "Uploading build artifacts to S3..."
      - aws s3 sync build/ s3://paynet-tgp-bucket-1/tgp-frontend-build/tgp-frontend-pipeline --delete
    

artifacts:
  files:
    - '**/*'  # Include all files in the repository
  base-directory: build